name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Swift
      uses: slashmo/install-swift@v0.1.0
      with:
        version: 5.10
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
